Repository jaredlyon/Operation-Politibot, pull requests merged in 2022-09, with the labels that each got.

#39 Fix Replies, Update Lock/Unlock to Slash Commands
  OpBot 13/commands/moderation/ban.js
  OpBot 13/commands/moderation/case.js
  OpBot 13/commands/moderation/casehead.js
  OpBot 13/commands/moderation/kick.js
  OpBot 13/commands/moderation/lock.js
  OpBot 13/commands/moderation/logs.js
  OpBot 13/commands/moderation/mute.js
  OpBot 13/commands/moderation/unlock.js
  OpBot 13/commands/moderation/warn.js
Labels: bug, enhancement

#40 update /suggest with modals
  OpBot 13/commands/moderation/suggest.js
  OpBot 13/index.js
Labels: enhancement

#42 Appeals System Implementation
  OpBot 13/commands/moderation/ban.js
  OpBot 13/commands/moderation/kick.js
  OpBot 13/commands/moderation/mute.js
  OpBot 13/commands/moderation/warn.js
Labels: enhancement

#45 update /mute and /ban
  commands/moderation/ban.js
  commands/moderation/mute.js
Labels: enhancement

#44 v2.0.1 - Initial v2 Patch
  commands/moderation/ban.js
  commands/moderation/case.js
  commands/moderation/casehead.js
  commands/moderation/mute.js
  commands/moderation/setcount.js
  events/clientEvents/messageCreate.js
Labels: bug, enhancement

#48 v2.1.0 - Reputation System
  .DS_Store
  .gitignore
  LICENSE.md
  commands/moderation/demographics.js
  commands/moderation/incident.js
  commands/moderation/ping.js
  commands/moderation/rep.js
  commands/moderation/repmod.js
  commands/moderation/report.js
  events/clientEvents/interactionCreate.js
  handlers/handler.js
  index.js
  repData.json
Labels: documentation

#63 #62 - Fix userinfo.js
  commands/moderation/userinfo.js
Labels: documentation

#66 #49 - fix messageUpdate
  events/clientEvents/messageUpdate.js
Labels: documentation

#72 #71 - Exclude bots from activity roles
  events/clientEvents/messageCreate.js
Labels: documentation

#75 #69 - Add rep logs
  commands/moderation/rep.js
Labels: documentation
