Repository jaredlyon/Operation-Politibot, pull requests merged in 2022-10, with the labels that each got.

#85 fixing it again
  commands/moderation/ban.js
  commands/moderation/kick.js
  commands/moderation/mute.js
  commands/moderation/warn.js
Labels: documentation

#88 #55 - Fix lock commands
  commands/moderation/lock.js
  commands/moderation/unlock.js
Labels: documentation

#89 #56 - Update repmod
  commands/moderation/repmod.js
  commands/moderation/setrep.js
Labels: documentation

#90 #81 - Fix rep leaderboard
  commands/moderation/rep.js
Labels: documentation

#91 #86 - Fix ban DM failure
  commands/moderation/ban.js
Labels: documentation

#92 Add Context Menus
  commands/contextmenus/citationreport.js
  commands/contextmenus/citereminder.js
  commands/contextmenus/reportmsg.js
  commands/contextmenus/rulesremindermsg.js
  commands/moderation/report.js
  events/clientEvents/interactionCreate.js
Labels: feature addition, frontend

#98 Sync interactionCreate.js
  commands/contextmenus/citationreport.js
  commands/contextmenus/citereminder.js
  commands/contextmenus/reportmsg.js
  commands/contextmenus/rulesremindermsg.js
  commands/moderation/report.js
  events/clientEvents/interactionCreate.js
Labels: documentation

#99 Add required "reason" when repping
  commands/moderation/rep.js
Labels: frontend, technical improvement
